name: Squash & release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload-resource-pack:
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install zip
        run: sudo apt-get update && sudo apt-get -y install zip

      - name: Zip contents of repository
        run: |
          zip -r MagicWorld-v${{ github.run_number }}.zip .
          mv MagicWorld-v${{ github.run_number }}.zip $GITHUB_WORKSPACE

      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ResourcePack-v${{ github.run_number }}
          files: MagicWorld-v${{ github.run_number }}.zip

      - name: Send Discord webhook
        uses: MineBartekSA/discord-webhook@v2.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'The new resource pack is now available on GitHub resources: https://github.com/${{ github.repository }}/releases/download/ResourcePack-v${{ github.run_number }}/MagicWorld-v${{ github.run_number }}.zip'
          username: 'Resource pack'
